version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - echo Installing dependencies...
      - pip install pylint flake8 mypy
  build:
    commands:
      - echo Running code analysis...
      - pylint src/ || true
      - flake8 src/ || true
      - mypy src/ || true
  post_build:
    commands:
      - echo Analysis completed on $(date)
artifacts:
  files:
    - analysis_results.json
    - '**/*'
